evaluate: 
  type: shell
  timeout: 5000
  shell: 
    entrypoint: "/bin/sh"
    command: 
      - "-c"
      - "/app/predictive-horizontal-pod-autoscaler -mode=evaluate"
metric: 
  type: shell
  timeout: 5000
  shell: 
    entrypoint: "/bin/sh"
    command: 
      - "-c"
      - "/app/predictive-horizontal-pod-autoscaler -mode=metric"
runMode: per-resource
