evaluate: 
  type: shell
  timeout: 5000
  shell: 
    entrypoint: "/bin/sh"
    command: 
      - "-c"
      - "/app/predictive-horizontal-pod-autoscaler -mode=evaluate"
metric: 
  type: shell
  timeout: 5000
  shell: 
    entrypoint: "/bin/sh"
    command: 
      - "-c"
      - "/app/predictive-horizontal-pod-autoscaler -mode=metric"
runMode: per-resource
# Default values, matching K8s Horizontal Pod Autoscaler defaults
downscaleStabilization: 300
interval: 15000
minReplicas: 1
maxReplicas: 10