site_name: Predictive Horizontal Pod Autoscaler
theme: readthedocs
nav:
- Home: 'index.md'
- Reference:
  - Configuration: 'reference/configuration.md'
  - Metrics: 'reference/metrics.md'
  - Models: 'reference/models.md'
