site_name: Predictive Horizontal Pod Autoscaler
theme: readthedocs
nav:
- Home: 'index.md'
- 'User Guide':
  - Metrics: 'user-guide/metrics.md'
  - Models: 'user-guide/models.md'
  - 'Sync Period': 'user-guide/sync-period.md'
  - 'Downscale Stabilization': 'user-guide/downscale-stabilization.md'
  - 'Minimum and Maximum Replicas': 'user-guide/min-max-replicas.md'
  - 'Initial Readiness Delay': 'user-guide/initial-readiness-delay.md'
  - 'CPU Initialization Period': 'user-guide/cpu-initialization-period.md'
  - Tolerance: 'user-guide/tolerance.md'
- Reference:
  - Configuration: 'reference/configuration.md'