apiVersion: jamiethompson.me/v1alpha1
kind: PredictiveHorizontalPodAutoscaler
metadata:
  name: dynamic-holt-winters
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  syncPeriod: 20000
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  models:
  - type: HoltWinters
    name: HoltWintersPrediction
    startInterval: 60s
    resetDuration: 5m
    holtWinters:
      runtimeTuningFetchHook:
        type: "http"
        timeout: 2500
        http:
          method: "GET"
          url: "http://tuning/holt_winters"
          successCodes:
            - 200
          parameterMode: body
      seasonalPeriods: 6
      storedSeasons: 4
      trend: "additive"
      seasonal: additive
