apiVersion: jamiethompson.me/v1alpha1
kind: PredictiveHorizontalPodAutoscaler
metadata:
  name: dynamic-holt-winters
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  models:
  - type: HoltWinters
    name: dynamic-holt-winters
    perSyncPeriod: 1
    holtWinters:
      runtimeTuningFetchHook:
        type: "http"
        timeout: 2500
        http:
          method: "GET"
          url: "http://tuning/holt_winters"
          successCodes:
            - 200
          parameterMode: query
      seasonalPeriods: 6
      storedSeasons: 4
      trend: "additive"
      seasonal: additive
  decisionType: "maximum"
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  syncPeriod: 20000
  downscaleStabilization: 30
