apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: tuning
  name: tuning
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tuning
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tuning
    spec:
      containers:
      - image: tuning
        imagePullPolicy: IfNotPresent
        name: tuning
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tuning
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: tuning
  sessionAffinity: None
  type: ClusterIP
