apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-holt-winters-example
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - '*'
- apiGroups:
  - metrics.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: simple-holt-winters-example
spec:
  template:
    spec:
      containers:
      - name: simple-holt-winters-example
        image: jthomperoo/predictive-horizontal-pod-autoscaler:dev
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  provisionRole: false
  config:
    - name: minReplicas
      value: "1"
    - name: maxReplicas
      value: "10"
    - name: predictiveConfig
      value: |
        models:
        - type: HoltWinters
          name: HoltWintersPrediction
          perInterval: 1
          holtWinters:
            alpha: 0.9
            beta: 0.9
            gamma: 0.9
            seasonalPeriods: 6
            storedSeasons: 4
            trend: additive
            seasonal: additive
        decisionType: "maximum"
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
    - name: interval
      value: "10000"
    - name: startTime
      value: "60000"
    - name: downscaleStabilization
      value: "0"
