name: main
on:
  push:
  pull_request:
  release:
    types: [created]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Lint, test and build
      run: |

        # Get tooling
        export PATH=$PATH:$(go env GOPATH)/bin
        go get

        # Lint and test
        pip install -r requirements-dev.txt
        make lint
        make format

        # Exit if after formatting there are any code differences
        git diff --exit-code
        make test

        if [ ${{ github.event_name }} == "release" ]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION="${{ github.sha }}"
        fi

        make docker VERSION=${VERSION}
    - name: Deploy
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      if: github.event_name != 'pull_request' && github.repository == 'jthomperoo/predictive-horizontal-pod-autoscaler'
      run: |

        if [ ${{ github.event_name }} == "release" ]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION="${{ github.sha }}"
        fi

        echo "$DOCKER_PASS" | docker login --username=$DOCKER_USER --password-stdin

        docker push jthomperoo/predictive-horizontal-pod-autoscaler:${VERSION}

        if [ ${{ github.event_name }} == "release" ]; then
          docker tag jthomperoo/predictive-horizontal-pod-autoscaler:${VERSION} jthomperoo/predictive-horizontal-pod-autoscaler:latest
          docker push jthomperoo/predictive-horizontal-pod-autoscaler:latest
        fi
